# Generated by Django 3.0.8 on 2020-07-29 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('project_class', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('1', 'Incomplete'), ('2', 'Complete')], default='Incomplete', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_tag', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('link_status', models.CharField(choices=[('1', 'Uncited'), ('2', 'Cited')], default='Uncited', max_length=64)),
                ('link_type', models.CharField(choices=[('1', 'Document'), ('2', 'Research')], max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
