# Generated by Django 3.0.8 on 2020-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_link_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_status',
            field=models.CharField(choices=[('Uncited', 1), ('Cited', 2)], default='Uncited', max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('Document', 1), ('Research', 2)], max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Incomplete', 1), ('Complete', 2)], default='Incomplete', max_length=20),
        ),
    ]
