# Generated by Django 3.0.8 on 2020-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200730_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_status',
            field=models.CharField(choices=[('Uncited', 'Uncited'), ('Cited', 'Cited')], default='Uncited', max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('Document', 'Document'), ('Research', 'Research')], max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=20),
        ),
    ]
